### ISSUE TITLE
Missing sounds/metal_clang.wav

### ISSUE THREAD

**Issue by cwm9cwm9** [phrack/ShootOFF#133]
Failed build assertion.  (I'm dmaul's brother-in-law).

**Comment by phrack** [comment]
Do you have an exception trace or a LOC for the failed assertion?

PS. Some of the video tests currently fail because there are cases where green is detected as red.

**Comment by cbdmaul** [comment]
The file was missing from his copy of master completely, I assumed that it was some new file that was never added to master by mistake, but I see it is in the repo.  This was probably just from a mis-synced local repo.

**Comment by phrack** [comment]
OK. I am marking this invalid and closing in that case.
