### ISSUE TITLE
Deduplication processor catches shots after resetting the shots

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#140]
I noticed this with click to shoot.  If I shoot at a specific place, I can shoot there again and have it pick up another shot.  If I shoot at a specific place and then reset, I can't shoot in the general area of that shot again until I shoot somewhere else.

**Comment by phrack** [comment]
I had the same problem earlier, but you beat me to the bug report.

**Comment by phrack** [comment]
Accidently closed this with the wrong commit.
