### ISSUE TITLE
Nothing but shots are visible in the session viewer

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#149]
Presumably there's supposed to be something visible, right?

<img width="531" alt="sessionviewer" src="https://cloud.githubusercontent.com/assets/5543934/9028266/40dcc764-3941-11e5-89c9-9d7928d39cd6.png">

**Comment by phrack** [comment]
Please upload the sessions.

**Comment by cbdmaul** [comment]
https://dl.dropboxusercontent.com/u/56848390/2015-08-02%2018.05.06.xml
https://dl.dropboxusercontent.com/u/56848390/2015-08-02%2018.03.48.xml
https://dl.dropboxusercontent.com/u/56848390/2015-08-02%2018.02.39.xml

**Comment by phrack** [comment]
Thanks, I'll categorize this and the other one now. Your sessions will make it _much_ easier to dupe.

**Comment by phrack** [comment]
Closed because it's essentially a dupe of #150.
