### ISSUE TITLE
Resizing a target with the mouse, then moving the target with the mouse causes the target to run away.

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#151]
Don't know if this is directly related to backgrounds or not.

Added savanna background.  Added plate rack and sized it down.  Went to move it and it jumped around and out of the arena.  When that happened, the plate rack and the background disappeared (Just returned to grey).

Now I can't change the background or add a target to it.

No exceptions thrown.

**Comment by phrack** [comment]
Hah! I'll see if I can dupe it tomorrow.

**Comment by phrack** [comment]
I have not duped the background issue, but I have duped the target issue. Interestingly, for any target on any canvas if you resize it with the mouse then try to move it with the mouse, the target runs away. This isn't a problem with other combinations:
- Resize with the mouse then move with the keyboard and it's fine
- Resize with the keyboard then move with the mouse and it's fine

It's only when you do both with the mouse that it runs way after a resize.
