### ISSUE TITLE
Bouncing target dialog is all out of proportion on high res screens

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#176]
I'm sure it just needs to be switched to auto scale like the other ones...haven't looked at the gui file yet.

**Comment by phrack** [comment]
That code is here: https://github.com/phrack/ShootOFF/blob/master/src/main/java/com/shootoff/plugins/BouncingTargets.java#L65

It's gotta be either line 71 or 113.

**Comment by cbdmaul** [comment]
change 113 to

final Scene scene = new Scene(bouncingTargetsPane);

the dialog is still ugly but at least everything fits in it now

**Comment by phrack** [comment]
This gets rid of some of the nicer margins on lower resolutions, but I'll take slightly ugly and functional over ugly and completely broken looking.
