### ISSUE TITLE
Add support for IP cameras

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#189]
https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-drivers/driver-ipcam

**Comment by cbdmaul** [comment]
is there rtsp support? rtsp is much more likely to be usable than mjpeg

**Comment by phrack** [comment]
Even if this doesn't, there appear to be other options:

http://stackoverflow.com/questions/820888/java-rtsp-client-server-library

I don't really believe them, but someone claims that xuggler supports it, which is what we are using to record videos in debug mode and play them back in unit tests.

**Comment by phrack** [comment]
This example works well for us: https://github.com/sarxos/webcam-capture/blob/master/webcam-capture-drivers/driver-ipcam/src/examples/java/FoscamMjpegPushExample.java.

**Comment by phrack** [comment]
Some dependencies listed here (http form apache);

https://github.com/sarxos/webcam-capture/blob/master/webcam-capture-drivers/driver-ipcam/pom.xml

Also need:

http://mvnrepository.com/artifact/com.github.sarxos/webcam-capture-driver-ipcam
