### ISSUE TITLE
Replace common TTS sequences with a voice actor

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#198]
- (DONE) Reload
- (DONE) Malfunction
- (DONE) Shooter, Make Ready
- (DONE) This training exercise requires a target with subtargets
- (DONE) This training exercise requires a dueling tree target
- (#226) And
- (#226) Shoot
- (#226) The numbers 0-9 (separately so they can be stitched together in software with "Shoot" and "And" to say things like "Shoot, 1, 4, and 5" or "Shoot 5, 5, 3, and 2")
- (DONE) Round over

**Comment by cbdmaul** [comment]
"Round over"?
Numbers

**Comment by phrack** [comment]
Added those two and a few more to the overall list.
