### ISSUE TITLE
I have no way of deleting anything from lists on my MBP running Windows (Projectors, targets)

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#211]
Very specific condition, but my MBP's "delete" key operates as Backspace in Windows, which means I have no delete key to delete anything.  Suggest providing an alternate key in addition to delete.

**Comment by phrack** [comment]
How about using backspace as delete too? Would be easy addition.

**Comment by cbdmaul** [comment]
I don't see a problem with that.  I could see backspace being the expected button for removing things anyway.
