### ISSUE TITLE
Mac OS X + JWS: Missing ShootOFF's Home Directory! ShootOFF's home directory /Users/(username)/.shootoff does not exist and could not be created. Now closing

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#212]
Browser was Safari.

**Comment by boom-headshot** [comment]
OS was OS X Yosemite 10.10.5

**Comment by phrack** [comment]
I am unassigning the milestone for now but will not close this yet. I spent about 4 hours on this yesterday and did find and fix several Mac only bugs, but never duped this specific issue.

**Comment by phrack** [comment]
I am going to have to close this because I can't dupe it to save my life. Hopefully if it is a more general problem a Mac OS X dev will come along and fix it.
