### ISSUE TITLE
Make calibration settings stick for recalibration

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#219]
It is really annoying that if you go back in to change the radio buttons or do a minor adjustment of the arena area that you lose your settings.

**Comment by phrack** [comment]
- (DONE) Radio button selection
- (DONE) Calibration target size and postion

**Comment by phrack** [comment]
I decided to attach this to 3.3. because it will be handy, it's a small and easy change, and it's easy to test.
