### ISSUE TITLE
Race condition on diagnostic messages in CameraManager

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#275]
We use Platform.runLater to set the labels but this is not thread safe.  If we go to remove the label later but it hasn't been set yet by the other thread, we fail to remove it and the diagnostic message remains forever.

I know how to fix it.

**Comment by cbdmaul** [comment]
Same problem with your mouseOnArenaLabel (and any others I don't know about).

**Comment by phrack** [comment]
You can find all of the calls to addDiagnosticMessage by right clicking the different versions in CanvasManager and clicking "Open Call Hierarchy".

**Comment by cbdmaul** [comment]
I know I'm just lazy

**Comment by phrack** [comment]
This is probably only a partial solution, but I suspect diagnosticFutures (CanvasManager line 87) should be a ConcurrentHashMap.

**Comment by cbdmaul** [comment]
I think my solution works well enough to close this without addressing that.  We can reopen if we get a bug.

**Comment by phrack** [comment]
I don't think this fix is sufficient and future proof unless you make the boolean fields volatile. I am quite confident that would do it.
