### ISSUE TITLE
non executable file Ubuntu 15.10

### ISSUE THREAD

**Issue by T2Ulpc** [phrack/ShootOFF#278]
In ubuntu 15.10 I get the warning -
The file '/home/t/ShootOFF.jar' is not marked as executable.  If this was downloaded or copied from an untrusted source, it may be dangerous to run.  For more details, read about the executable bit.
So I am unable to run ShootOff due to this safety measure.
Is there a way to make this work? 

Thanks 
T.U.

**Comment by phrack** [comment]
You have two options:
- Right click the JAR, go to properties, then go to the Permissions tab. Check "Allow executing file as program." 
- Open a terminal, cd to the directory ShootOFF.jar is in, and run the following command: java -jar ShootOFF.jar

Make sure you are running Java 8 with JavaFX (i.e. new OpenJDK or install the latest Oracle JRE from a ppa - -  our wiki page on setting up dev environment on Ubuntu has some pointers for this). Second option is best way to get diagnostic messages if something goes wrong.
