### ISSUE TITLE
Autocalibration tests fail

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#321]
My tweaks to autocalibration broke the tests.  Need to fix.

**Comment by phrack** [comment]
OK, I am going to merge anyway under the assumption this will be fixed this weekend since it breaks the build. That's typically a huge no, but I think we are close enough to finishing 3.6 that I am OK with a broken build for a day or two.

**Comment by cbdmaul** [comment]
Closed via fb899eadbbc0dd1f92f3543010ccc6a74867b517
