### ISSUE TITLE
False green shots are detected when objects move around the projection arena.

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#329]
e.g. Bouncing Targets produces a large number of false green shots.

ShootOFF already warns when there is a lot of motion. A lower threshold could be used to apply a mask representing what is on the projection arena to the feed when auto-calibration has succeeded. This would factor our all pixels that are known to be the result of the arena when detecting a shot.

**Comment by phrack** [comment]
Current status: masking didn't really work because we didn't have a great solution to account for the delay between when the computer sends a frame to the projector and when that frame is actually shown. Our next idea is to use IR and filter visible light.

**Comment by cbdmaul** [comment]
Adjusting the exposure down seems to be a very good fix for this.  I suggest closing this, opening "auto camera adjustment" as a new issue.  Maybe add an extra part to "Excessive motion" that says, "turn down your damn exposure"? Maybe only during exercises with motion?

**Comment by phrack** [comment]
Have you tested changing the exposure from OpenCV on Windows? If so I'd like to see that it works on Linux too before the issue change.

**Comment by cbdmaul** [comment]
Regardless, I think the warning is our best bet.  We are never going to fix this without camera adjustment, automatic or not.

**Comment by phrack** [comment]
Totally agree the warning should be more actionable, just pointing out that there isn't enough info yet for me to be comfortable making an issue change in the short term.

**Comment by cbdmaul** [comment]
It does work on Windows, tested on ocam/c270

**Comment by phrack** [comment]
It works on Linux with the HD-3000, but it's not really clear what the values mean. I set both auto-exposure and exposure to zero and it was really weird, but it did do something that resembled a lower exposure rate strongly.

I'll close this issue once I change the motion message to suggest lowering the webcam's exposure.
