### ISSUE TITLE
Par drills don't allow easy entry of decimal par time

### ISSUE THREAD

**Issue by edwardkort** [phrack/ShootOFF#375]
I really shouldn't code late at night...

The current validation of the par time, in gui.controller.ParIntervalController, does not allow entry of a decimal point in a blank field. Line #36 should read:
    if (!newValue.matches("[0-9]_\.?[0-9]_")) {

The downside of this regular expression is that a blank field is valid, although that is the same behavior as the other text fields. However, internally the drill then uses the default value (2.0), so the behavior is consistent and functional.

Sorry again,
Edward Kort

**Comment by phrack** [comment]
Bugs happen. Thanks for pointing out the problems and fixes, I'll go ahead and push them real quick to save you the trouble of a pull request.
