### ISSUE TITLE
Entire target menu for projector arena not working

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#377]
In master I am unable to add projector targets.  No errors, just nothing happens.

Courses add targets just fine.

**Comment by phrack** [comment]
This is a total WTF. The code to add the targets was removed in this commit:

https://github.com/phrack/ShootOFF/commit/0a6e9216bc24bf99de1cc63719583bf23aa0899b#diff-a4f20fd1d632a7d0e0da6986506405d5

The merged commits are both yours, but you don't remove the code in either one and neither do I. As far as I can tell, the formating got super fucky in one of them (the code was still there though) and this made it different enough between the two that the merge decided to just nuke it.

**Comment by cbdmaul** [comment]
that is really strange.  it's not even a multiple line complicated merge.  just straight up deletes a line.

i blame the Illuminati
