### ISSUE TITLE
Shot markers being removed by reset causes false shots

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#378]
Shot detection re-activated too quickly after reset likely culprit (There's no expectation that our shot detection would prevent these false positives).

**Comment by phrack** [comment]
Is this a side effect of masking making things take longer?

**Comment by cbdmaul** [comment]
I don't think so, I believe this has always happened to me.  The masking might fix this but masking will only happen if there is auto calibration so we should fix it anyway.

**Comment by cbdmaul** [comment]
Having looked at this again, do we disable shot detection for reset? I can't find the code for it.

**Comment by phrack** [comment]
https://github.com/phrack/ShootOFF/blob/master/src/main/java/com/shootoff/gui/controller/ShootOFFController.java#L967

I will test it.

**Comment by cbdmaul** [comment]
This still happens.

**Comment by cbdmaul** [comment]
Ugh.  Even extending it to a second isn't enough if there are shot detection processing delays like bright pixels.

**Comment by phrack** [comment]
This seem to have dependencies on camera settings and such because I can't dupe it.

**Comment by cbdmaul** [comment]
I haven't seen it either, let's close it
