### ISSUE TITLE
Motion tweaks broke shot detection after calibration

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#398]
We really can't catch a break here...

Not sure if it's 

237df50fd2824951b66424fdbc3261599d368628

or 

39695e3af8c34888d4f880752c094596baa29369

Either way, shot detection works fine before calibration but after calibration it doesn't work at all anymore. Even more, everything seems completely shifted off. Note in the attached screenshot how it is complaining about the brightness of the targets but it draws them in completely the wrong place. I duped this in three different sessions and confirmed the camera never moved.

![screenshot from 2016-03-02 08-08-48](https://cloud.githubusercontent.com/assets/174818/13461356/e1ed7590-e04e-11e5-9ad1-2197c8a38deb.png)

**Comment by cbdmaul** [comment]
I think I know what the issue is for it not displaying the red in the right place.  But shot detection should not have been affected in a negative way.

**Comment by cbdmaul** [comment]
`   // This function ADJUSTS X AND Y FOR LIMITING DETECTION BOUNDS
    private void drawOnFrame(Mat frame, int x, int y, byte[] color) {
        int drawX = x;
        int drawY = y;

```
    if ((cameraManager.isLimitingDetectionToProjection() || cameraManager.isCroppingFeedToProjection())
            && cameraManager.getProjectionBounds().isPresent()) {
        drawX = (int) (cameraManager.getProjectionBounds().get().getMinX() + x);
        drawY = (int) (cameraManager.getProjectionBounds().get().getMinY() + y);
    }

    frame.put(drawY, drawX, color);
}`
```

This function does not need to adjust for bounds anymore, because processFrame does it.  So we can drop the whole if.
