### ISSUE TITLE
Exercise Manager Description column width

### ISSUE THREAD

**Issue by ifly53e** [phrack/ShootOFF#415]
When expanding the exercise manager window, the description column width remains the same and the description text is still cut off (column should expand with the window).  Dragging the column to increase the width to the new window size brings in a scroll bar, but the column width remains the same and the user still does not get the full description.  Double clicking on the description column will expand the column fully within its constant width bounds, but the text is centered and the "Description" header is lost off the screen.  Request normal window behavior for the description column so the full description can be read when the window is re-sized, or word wrap the description with a vertical scroll bar for the exercise row to accommodate long descriptions.

**Comment by phrack** [comment]
It sounds like we need at least two approaches:
1. Make the TableView expand with the Window and always expand the description column not the others when stretching.
2. Try to make each entry at least twice as tall to accomodate more text right away.
