### ISSUE TITLE
Anchors on targets in projection arena stuck on

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#437]
<img width="701" alt="anchorbug" src="https://cloud.githubusercontent.com/assets/5543934/14236993/899167b0-f9eb-11e5-92a5-ee7ccc4891ab.png">

Possibly I didn't deselect the target before moving the cursor out of the arena.  Then I couldn't get rid of the anchor on that target (I did not try deleting the target).

No exceptions seen.

**Comment by phrack** [comment]
They only get stuck on if there is no background. I am guessing this is because there was nothing for us to register a click on to know we need to turn off the selection stuff. Will look into it.
