### ISSUE TITLE
Behavior of "Save Feed Image.."

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#451]
Not sure if intentional/bug but unusual behavior in my opinion:
1.  It saves the entire window, not just the feed.  If this is intended, maybe it should be renamed.
2. It appends ".png" twice when I save a file.  So if I put in "sample" I get "sample.png.png"
3. It should capture the image when you click the button, not when you click to save.

**Comment by phrack** [comment]
1. Was because when I was implementing that feature I stubbed it out using the most simple way to get an image of the feed and apparently forgot to try to more narrowly target it (this may not be easy).
2. and 3. are bugs.
