### ISSUE TITLE
If possible, resize anchors should stay a consistent and sane size

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#458]

**Comment by cbdmaul** [comment]
Still seeing this if I make perspective changes?

<img width="624" alt="hugeresizeanchor-afterperspectivechange" src="https://cloud.githubusercontent.com/assets/5543934/16605002/fea59bba-42f8-11e6-81cf-1d56546fed7f.png">

**Comment by phrack** [comment]
OK, I only had half the solution. I forgot that there are actually two places targets are scaled and my new tag is only respected in one of them. `TargetView.setDimensions` is the remaining culprit.

**Comment by phrack** [comment]
It's also probably a bug that right clicking a target selects it for resizing purposes. That doesn't happen in most drawing programs for example.

**Comment by phrack** [comment]
There are actually two problems here:
1. If you call setDimensions it doesn't respect the resizable = false tag. I tried doing the same thing that works for resizing with the mouse and for some reason it isn't work for me. I am probably tired and missing something small so I'll try again with a fresh slate some other time since this isn't super important (the dragging with the mouse case is far more important and that is fixed).
2. If you resize a target, unselect it, then reselect it the anchors get shrunk or expanded based on the target group's overall scale. Trying to scale it the other way to keep a consistent size (this is what the mouse solution, which works, does) is not working for some reason. For some reason the scale is being ignored when I am adding the anchors.
