### ISSUE TITLE
Undeterministic or failing auto calibration test results?

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#476]
Our build failed last night, but those tests are passing for me.

I did a project update, and one test failed the first time...but worked after that.  I'm wondering if there is something undeterministic here.

**Comment by phrack** [comment]
This is pretty consistent in travis for some reason.

**Comment by cbdmaul** [comment]
Do they work for you?

**Comment by phrack** [comment]
These autocalibration tests are fairly consistently failing for me as are the perspective tests now failing in travis too. For the latter, I think you revised some calculations that changed results and the perspective tests weren't updated to account for that.

**Comment by phrack** [comment]
PS. The autocalibration ones are failing because pixels (usually early on) don't match. For example, for testCalibrateProjection it fails at 0, 0 because imgA is -12640756 and imgB is -12574702. Maybe a test resource isn't updated in the repo?

**Comment by cbdmaul** [comment]
My copy is up to date and everything is committed.  Tests pass.

**Comment by cbdmaul** [comment]
We still have this problem, possibly due to architecture differences in opencv.

**Comment by phrack** [comment]
Fixed for me. Suppose we can wait to close this until Travis agrees.

**Comment by cbdmaul** [comment]
Yeah, I was waiting for it but I've got to go.

**Comment by phrack** [comment]
I am going hiking today but the test should finish before I leave. I'll close it.
