### ISSUE TITLE
Add button to open camera settings dialog

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#498]
Now that we are using opencv, we can invoke the camera's native settings dialog with:

camera.set(CV_CAP_PROP_SETTINGS, 1);

It would be very useful to have a button for this somewhere.

**Comment by phrack** [comment]
Not too surprising, but this doesn't work on Linux and I doubt it does on Mac either -- you get a "property unsupported" error. Assuming it does in fact work on Windows, I suggest adding it to the right click menu for camera feeds now via a "Configure Camera" button. The code to add this button should only execute if the OS is Windows (check the Main.main to see how to do that).

**Comment by phrack** [comment]
PS. This should be so quick and easy to do I suggest just doing it in 3.8 if the feature works on Windows.
