### ISSUE TITLE
CameraFactory.defaultCamera is only ever set to null

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#528]
This is possibly removable, but it seems like there might be a bug instead. This field used to be used to permanently store the default camera for a ShootOFF execution on Mac because once you found the default camera once, you wouldn't find it again. Fuck Mac.

**Comment by cbdmaul** [comment]
Why did we lose this LOC?

https://github.com/phrack/ShootOFF/blob/v3.8-FINAL/src/main/java/com/shootoff/camera/Camera.java#L98

I'm going to re-add it but obviously I don't have OSX to test it with.

**Comment by phrack** [comment]
I have no idea where it's lost but it was lost post 3.8. It's there in every commit up to the 3.8 tag.

**Comment by phrack** [comment]
68d01c4ff14edfdc2b4f585e030d40d492b28f68
