### ISSUE TITLE
Checkboxes do not return after renaming a camera on preferences slide

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#564]
- [x] Ensure camera tab name is changed even if camera config did not change aside from a camera's name

**Comment by cbdmaul** [comment]
This only happens on Windows if you don't hit enter in the box fyi.

**Comment by phrack** [comment]
I am getting this even if I hit enter on Linux. I think there is a bookkeeping issue with the camera names map.

**Comment by phrack** [comment]
FUUUUUCK I HATE THIS GUI CODE

This code works as expected IF the camera is checked. The solution is to make it so that it's not editable unless  the checkbox is checked. The following code at the top of on mouse clicked handled for a list cell seems to do that well enough:

``` java
                if (!fetchWebcamChecked(getText())) {
                    this.setEditable(false);
                    return;
                }

                if (event.getClickCount() > 1 && fetchWebcamChecked(getText())) {   
                    this.setEditable(true);
                    startEdit();
                }
```

The problem is that within the same session of ShootOFF the mapping between the renamed camera old camera name isn't maintained so it thinks the new name is a new camera when you re-open the preferences.

**Comment by phrack** [comment]
This all so fucking obnoxiously overcomplicated because JavaFX gives you NO WAY to map a new item to a ListCell. You can't even say something simple like, "Hmm, I want the ListCell who's text is x" because obviously that'd be too convenient.

This means you never have any way to know which cell belongs to which camera, so you have to do all kinds of extra fucky bookkeeping to implement any kind of non-trivial functionality.

SO is full of people bitching about this too, but of course we have an unusually complicated case.
