### ISSUE TITLE
Clay busters does not turn off when starting calibration

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#566]
This is a general problem with exercise controls and calibrating.

**Comment by cbdmaul** [comment]
Also, courses and other targets remain on the arena when clay busters is launched.

**Comment by phrack** [comment]
That's expected. No exercise clears this for you and they don't even have the ability to do so. It's two button clicks to do this yourself, and if we add it to exercises it WILL get abused.

**Comment by phrack** [comment]
What I am going to do here is if there is a set exercise when calibration starts, I am going to save which one is set, unset it, then reset it (meaning the exercise will start from scratch) when calibration stops. 

If you want to go farther in a separate issue, go head. I will still think it's unwise to let exercises clear courses, but I won't stop it.
