### ISSUE TITLE
camera window appears to be hidden by shot table when adding a new camera

### ISSUE THREAD

**Issue by ifly53e** [phrack/ShootOFF#574]
Not sure why, but there were times when I was testing with the new PS3Eye code and the camera window seemed like it was hidden behind the shot table.  I could hear the brightness and movement warnings but the camera pane was not there.  After I resized the window (sometimes vertically would do it, sometimes horizontally would do it) the camera pane would appear.

This was mostly when a new camera was added.  After the camera was saved to the preferences, this was not as reproducible.

**Comment by cbdmaul** [comment]
I have seen the same issue.

**Comment by phrack** [comment]
Please check to see if the fix for #565 fixed this. I fixed three different bugs that were causing #565 that could also have caused this.

PS. Attach a screenshot if it's not fixed please.

**Comment by phrack** [comment]
Anyone confirm? @ifly53e? @ beuller? @ beuller?

**Comment by ifly53e** [comment]
Can't download the latest nightly for some reason...is it my work firewall?

**Comment by phrack** [comment]
Might be, it's downloading at my house.

**Comment by ifly53e** [comment]
After downloading the nightly and running for the first time with no external cameras and only the webcam on the laptap as the only cam, the camera window is still hidden until you collapse the main window fully horizontally...when you expand the window, the camera window is shown but not at full size.

**Comment by phrack** [comment]
This bullshit only dupes on Windows and only if the screen resolution is >1280x800.

**Comment by phrack** [comment]
This is fixed in my VM, thus I am going to make the wild and dangerous assumption that it is fixed everywhere.
