### ISSUE TITLE
Add support for infrared labeled shots

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#579]

**Comment by cbdmaul** [comment]
I have a solution for this other than how to handle the XML sessions since they store shot colors as actual RGB shot values.  I'd rather everything used an enum

**Comment by cbdmaul** [comment]
ShootForScore also a problem

**Comment by phrack** [comment]
Shot color should just be an enum since we won't be seeing arbitrary colors.

**Comment by cbdmaul** [comment]
I did that part already, just waiting on how to handle xml / shootforscore
