### ISSUE TITLE
No webcam found error when only PS3Eye plugged in

### ISSUE THREAD

**Issue by ifly53e** [phrack/ShootOFF#595]
Before forceclose, maybe add a check to see if there is a ps3eye plugged in?

**Comment by phrack** [comment]
Shouldn't the PS3eye initialization method in Main.start() call CameraFactory.registerCamera? That would solve the problem and it's what the registerCamera method is for.

**Comment by ifly53e** [comment]
It does...So not sure why this is happening then

**Comment by phrack** [comment]
Yea, weird. I actually don't see any reason in the code this should happen. @cbdmaul is at my house now so we can test with the PS3eye he brought soon.

**Comment by ifly53e** [comment]
Use a desktop with no default cam if you can.

**Comment by cbdmaul** [comment]
Default cam was only pulled from webcam-capture, ignoring registeredCameras.  Fixed.
