### ISSUE TITLE
Arena tab view shot hits are not removing targets in Bouncing Targets when they should.

### ISSUE THREAD

**Issue by ifly53e** [phrack/ShootOFF#601]
Start ShootOFF in debug mode.
Start Projector.
Start Bouncing Targets.
Check Remove hit targets in the options.
Activate the Arena Tab view.
Shift click on Grey target.  Score increases but target is not removed from Arena tab view or the Projector Arena.
Activate the Default Tab view.  Shift click on the Grey target so it is hit in the projector view.  Target is removed in both Arena tab and Projector views.

Shouldn't the Arena Tab View shot hits cause the target to be removed like they are in Default Tab View shot hits?

**Comment by phrack** [comment]
Yea, it looks like the injected shot isn't being handled quite right when it starts from the arena tab.
