### ISSUE TITLE
Oddities with perspective scaling

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#604]
<img width="1440" alt="bug-perspective" src="https://cloud.githubusercontent.com/assets/5543934/19010142/d64a856e-8749-11e6-8254-3f3cb725adc3.png">

These two targets have identical parameters.  If I change height and change it back to 216, I get the size on the left.  If I change width and change it back to 279, I get the size on the right.

The one on the right (the bigger one) is the correctly sized one (Well, not perfect, but as correct as our math and measurement of the paper pattern is right now).

**Comment by cbdmaul** [comment]
I would think this would be on the GUI side, as the perspective side is literally one function at that point and I don't see how you could possibly have undeterministic output from it.

**Comment by cbdmaul** [comment]
This has to be in setDimension.  calculateObjectSize is always given the correct information and returns the correct value.

**Comment by cbdmaul** [comment]
Yeah it has to do with what of the scaling functions in setDimension get called.  Changing height works as expected.  Changing width results in the too small target.  Any ideas?

**Comment by phrack** [comment]
That's weird because the width calculation looks right but the height one is using `scaleX` where it's probably supposed to use `scaleY`: https://github.com/phrack/ShootOFF/blob/master/src/main/java/com/shootoff/gui/TargetView.java#L246 . I'd expect height to be wrong and width to be right.

**Comment by cbdmaul** [comment]
I probably confused the two.  if there's a bug that's probably the source.
