### ISSUE TITLE
Camera thread not closing on exit

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#611]
Don't know why I'm suddenly having this opencv issue but it happens every time with my c270 right now.  Camera works fine otherwise.

Thread [Shot detection Logitech HD Webcam C270 1 com.shootoff.camera.shotdetection.JavaShotDetector](Suspended)  
    owns: SarxosCaptureCamera  (id=71)  
    VideoCapture.isOpened_0(long) line: not available [native method]  
    VideoCapture.isOpened() line: 268  
    SarxosCaptureCamera.isOpen() line: 131  
    SarxosCaptureCamera.run() line: 189 
    Thread.run() line: 745

**Comment by cbdmaul** [comment]
Oddly, the arena window stays open (frozen)

**Comment by phrack** [comment]
I am getting the same thing. ShootOFF doesn't close at all anymore, it just freezes on close.

**Comment by phrack** [comment]
I synchronized a method that wasn't synchronized before because `closing` was guarded half the time but not in there: https://github.com/phrack/ShootOFF/commit/24241694ff2b990eaa65ca44c759c060fa269956. Might have broken something?

**Comment by cbdmaul** [comment]
might be causing #609 also? never had that before either

**Comment by phrack** [comment]
Yes, it's causing both. The right answer seems to be to make `closing` atomic instead.
