### ISSUE TITLE
Replace passing Mat of new frame around with a Frame object

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#613]
Since we pass the Mat around, the frame timestamp, for one, is kind of arbitrary and passed around oddly.

I propose (and intend) to replace this mechanism with a Frame object that contains the frame and the timestamp set by the issuing camera class.  For Optitrack, this will be the actual frame timestamp from the camera itself.

This will also be a good place to put functions related to getting a copy of the frame, changing the frame's cvtype, etc.  So that is centralized as well.

**Comment by phrack** [comment]
This was fixed by pull request #617
