### ISSUE TITLE
Cant use Projector

### ISSUE THREAD

**Issue by ronil9** [phrack/ShootOFF#618]
Please help. Cant setup projector. when clicking "projector", it will open new tab "projector arena" with error needs calibration.

shootoff ver 3.9

**Comment by phrack** [comment]
You've given us basically nothing to go on, so I'll have to give a generic answer. If you're seeing "Needs Calibration" either:
1. Your projector is not connected to your computer and on.
2. The arena was not able to find the projector, in which case you will have to manually move the arena to the projector display and hit F11.

Suggested viewing:

https://www.youtube.com/watch?v=xT8jWLTeSVo
https://www.youtube.com/watch?v=T-m8Yd6XKv0
https://www.youtube.com/watch?v=oU_Pu7RRMjM

Suggested reading:

https://github.com/phrack/ShootOFF/wiki/Using-the-Projector-Arena

If none of that solves  your problem, attach a screenshot.
