### ISSUE TITLE
matToBufferedImage Exception with PS3eye

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#637]
http://i801.photobucket.com/albums/yy299/SammyWI/debug.jpg

**Comment by cbdmaul** [comment]
Guessing an invalid frame slipped through.  Unless there looks like a bug, probably just catch the exception and treat it like a null frame.

**Comment by phrack** [comment]
I agree. Looking at the code, they do a lot of reasonable things to check for invalid frames. This particular exception is thrown if even something they didn't expect happens (it is from the method's catch all block). Therefore we can do nothing but what you said, catch it, log it, and move on to the next frame.
