### ISSUE TITLE
Camera recommendations?

### ISSUE THREAD

**Issue by dogweather** [phrack/ShootOFF#647]
Hi, I remember hearing a recommendation in one of the videos, but forget which one that was. 

Any particular cameras found to be better or worse? Any particular framerate or resolution to shoot for? I can update the wiki with the info.

I also have both Mac and PC's at home, and am thinking about which platform might work out best.

**Comment by phrack** [comment]
https://github.com/phrack/ShootOFF/wiki/FAQ#what-webcam-should-i-buy-

Most standard webcams will max out at about 30 FPS, which is perfectly fine for recoiless training. If you are using recoil with a system like coolfire you're going to need more like 120 FPS to get reliable results. Any PC that was decently top of the line within the last 3-4 years will easily get 30 FPS with ShootOFF.

Windows has the best support, Linux is a close second, and Mac is a more distant third. The webcam driver situation on Mac is pretty awful.
