### ISSUE TITLE
No sound for green laser

### ISSUE THREAD

**Issue by edwardkort** [phrack/ShootOFF#651]
ShootOFF 3.10, Windows 10. I just got a SIRT with green laser (first time I've tried green). No matter what combination of selections in the Preferences for Ignore Laser Color, Red Laser Sound, Green Laser Sound, or the sound file selection boxes, green laser hits give me no sound.

Red laser hits produced sound fine. And the green laser hits are registering just fine in the shot table and target display. I have tried many universal exercises with the same result. I don't have a projector, so that wasn't tried.

I seem to recall there being an issue in the past, but could find it on Reddit.

Thank you,
Edward Kort

**Comment by cbdmaul** [comment]
Line 554, CanvasManager

`			} else if (config.useGreenLaserSound() && Color.GREEN.equals(shot.getColor())) {`

Color should be ShotColor
