### ISSUE TITLE
Allow for a configurable offset for detected shots to account for poorly aligned cartridges

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF#679]
> Hi! I have different lasercartridges wich I use in Shootoff with different weapons. Pistol, carbine and some more. They all have the same problem, they are hard (impossible) to align when they are inserted in the chamber of the gun. When I use FATS and Lasershot there is a function wich help me to align in the software. I click on a button and a cross appears. I aim in the center of the cross and make a good shot. The software then remember my alignoffset and correct all my hits then when I´m shooting. Do you fantastic codehacker think this is possible to do in ShootOFF? Regards Fredrik

https://www.reddit.com/r/ShootOFF/comments/5wnmh2/aligning_the_laser_in_shootoff/

**Comment by cbdmaul** [comment]
Is this the same as #661?

**Comment by phrack** [comment]
Indeed. I'll merge this one into #661.
