### ISSUE TITLE
ShootOFF-diagnostics.jar crashing...

### ISSUE THREAD

**Issue by zestysoft** [phrack/ShootOFF#684]
When opening ShootOFF-diagnostics,jar (v3.10-final), it starts fine, I can see my webcam and then after a few seconds I hear a sound and it disappears.

Here's the head of the log file:
`Localhost hostname lookup failed, keeping the value 'unavailable'
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.getsentry.raven.event.EventBuilder$HostnameCache.updateCache(EventBuilder.java:620)`

Not sure what's broken -- my dns is working fine?  Is there an entry I can put in the hosts file to temporarily bypass this issue?

nslookup localhost:
`Server:  pfSense.intranet.redacted.com
Address:  192.168.1.1

Name:    localhost.intranet.redacted.com
Addresses:  ::1
          127.0.0.1`

nslookup 127.0.0.1:
`Server:  pfSense.intranet.redacted.com
Address:  192.168.1.1

Name:    localhost
Address:  127.0.0.1`

Runtime: Java(TM) SE Runtime Environment 1.8.0_121-b13 64-bit
OS: Windows 10 10.0 amd64, Patch Level: 
Max amount of memory JVM will use = 7269 MB
Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
 is64bit = false
 physical cpu(s): 4
 logical cpu(s): 8
CPU Load Per Processor: 19.83% 11.10% 15.15% 14.79% 14.45% 12.13% 15.02% 13.25%
Total RAM Installed: 32706 MB
Available RAM: 28030 MB

**Comment by cbdmaul** [comment]
You just need to run the Shootoff-Diagnostics-Diagnostics.jar

My knowledge of this area is jokes only

**Comment by phrack** [comment]
Looks like we need to update the Sentry libraries it is using. In any case, all it didn't do was send us shootoff-diagnostics.log, which can be done manually.

**Comment by phrack** [comment]
I just put out a new version of the diagnostic tool with the newest Sentry libraries:

https://github.com/phrack/ShootOFF-diagnostics/releases/tag/v1.3-FINAL

I also checked that instance of Sentry is running fine. That seems to be everything checkable on our end. 

If you continue to have problems, it is using HTTP to communicate with dev.shootoffapp.com:9000.
