### ISSUE TITLE
Enabling steel challenge without course warns user to add course, but does nothing when course is added

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#699]
This is a usability issue.  It's not clear why shot detection doesn't work and never comes back unless you switch training.

**Comment by phrack** [comment]
Somewhere along the line refactoring broke target updates so now training exercises never get them. The logic in steel challenge is fine. I don't really know what refactoring broke it.

**Comment by phrack** [comment]
ec3c2136a514a9334e4ac53c73f1b71f9095c3bc
