### ISSUE TITLE
Using ShootOFF with Projector as Main Computer Display (Mac)

### ISSUE THREAD

**Issue by apnea1963** [phrack/ShootOFF#703]
My Mac mini is a HTPC connected to a projector as it's only display. Is it possible to use the ShootOFF arena in this configuration or does ShootOFF need to see the projector as a second display?

**Comment by phrack** [comment]
If you only have one display you will not be able to see the main ShootOFF window AND the arena at the same time. ShootOFF will calibrate off the one screen when you open the arena and you will get a lot of false shots any time you alt+tab to the main window for any reason.

The alternative is to use headless mode. Start ShootOFF with the -h switch and use this Android app: https://drive.google.com/open?id=0B-LqhPLh8wFzSWJEdlBTY3dJbk0. Of course, this assumes you have an Android device.

**Comment by apnea1963** [comment]
Thanks for that. I'm on a Mac. On Amazon, I found a device that will emulate an external monitor for use in running in headless mode. It connects to the display/Thunderbolt port. Mini DP - DisplayPort display emulator EDID emulator Plug. I plan to connect this emulator and control the Mac remotely. It should show as having two displays, the emulated display and the projector.
