### ISSUE TITLE
installed exercises don't show up

### ISSUE THREAD

**Issue by captainpaint** [phrack/ShootOFF#704]
just recently installed shootoff. I am running windows 10, 64 bit. I went to "training" and "get exercises" and installed all the add ons but they don't show up in training. what am I doing wrong?

**Comment by phrack** [comment]
Two possibilities come to mind:

- ShootOFF is installed in a place that requires administrative privileges but it wasn't run as an administrator. Thus, the install didn't actually happen. ShootOFF doesn't need administrative privileges so it could just be moved somewhere else.
- Projector exercises were installed but the projector section was collapsed (you'd have to click the projector text or the arrow by it to expand it).
