### ISSUE TITLE
Shots are moved away from where they are actually seen

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#73]
![shotdetection-bug](https://cloud.githubusercontent.com/assets/5543934/7898799/52395de0-06da-11e5-99fc-f54a640008c6.png)

It is detecting shots but then moving them away from where they appear on the camera feed
In the screenshot, the shots are in the blue but it moves them to the white area consistently.

**Comment by phrack** [comment]
Probably due to approximating the center of the shot.

**Comment by phrack** [comment]
Approximating the center of a shot is using the webcam image and not the mask.
