### ISSUE TITLE
Clicking on a target in the arena makes it jump way to left and a bit towards the top

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#79]
Seems to jump to the origin (0,0) or near the origin unless it is already near the orgin

**Comment by cbdmaul** [comment]
Clicking on a plate rack made it jump and totally screwed up all the pieces of it

**Comment by cbdmaul** [comment]
Followup: Seems to jump equal to the distance of the offset of where i click on the target relative to the center of that target

**Comment by phrack** [comment]
This happened with the calibration rectangle earlier, I forgot to open an issue.
