### ISSUE TITLE
Speech seems to get cut off

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#80]
I'm on the random shoot protocol.

It is attempting to say "Shoot Two" but it sounds more like "Shoot Tn--"

**Comment by phrack** [comment]
Might need to see if there is a way to spell it where it gets it phonetically right.

**Comment by phrack** [comment]
I am marking this one won't fix. This voice is bad at saying "two" and no spelling of it or words that should sound like it makes it really any better. It seems good enough for now and we can try a different voice at some other date.
