### ISSUE TITLE
Pepper popper does not fall when shot sometimes

### ISSUE THREAD

**Issue by cbdmaul** [phrack/ShootOFF#87]
![pepperpopper-notfalling](https://cloud.githubusercontent.com/assets/5543934/7902013/3d965614-0774-11e5-9a42-397ddaf8aa32.png)

It makes the sound but does not fall.  Possibly related to target moving bug #79

**Comment by phrack** [comment]
There is no clear reason this shot was missed. To close the issue while doing something useful, I added debug logging for shot processing which should help figure out what is going on if this happens again in the future.

Debug logging is turned on by simply turning on debug mode in ShootOFF. In Eclipse right click in the Package Explorer and hit Run As -> Run Configurations... and add --debug to Program arguments in the Arguments tab.
